def show_menu():

    print()
    print("JAMES TRADING PLATFORM")
    print("======================")
    print("1 View Platform")
    print("2 Change Price")
    print("3 Suspend Selection")
    print("4 Suspend Event")
    print("5 Settle Market")
    print("6 Void Market")
    print("7 Suspend Market")
    print("8 Unsuspend Selection")
    print("9 Unsuspend Market")
    print("10 Unsuspend Event")
    print("11 Search")
    print("12 Create Event")
    print("13 Create Market")
    print("14 Create Selection")
    print("15 Create Template Event")
    print("16 View Audit Log")
    print("17 Delete Selection")
    print("18 Delete Market")
    print("19 Delete Event")
    print("20 Add Client")
    print("21 View Clients")
    print("22 View Event")
    print("23 Book Event For Client")
    print("24 View Client")
    print("25 Unbook Event For Client")
    print("26 Publish Event")
    print("27 Exit")
    print()

    choice = input("Choice: ")

    return choice